-- ============================================================
-- 03_build_analytics.sql
-- Builds ANALYTICS marts + KPI views (Power BI friendly)
-- ============================================================

USE WAREHOUSE COMPUTE_WH;
USE DATABASE ECOM_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- ------------------------------------------------------------
-- Dimensions
-- ------------------------------------------------------------

-- Date dimension (from orders purchase dates)
CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE AS
WITH d AS (
  SELECT DISTINCT CAST(ORDER_PURCHASE_TS AS DATE) AS DATE_KEY
  FROM STG.ORDERS
  WHERE ORDER_PURCHASE_TS IS NOT NULL
)
SELECT
  DATE_KEY,
  YEAR(DATE_KEY)                        AS YEAR,
  MONTH(DATE_KEY)                       AS MONTH,
  DAY(DATE_KEY)                         AS DAY,
  DAYOFWEEKISO(DATE_KEY)                AS DOW_ISO,
  WEEKOFYEAR(DATE_KEY)                  AS WEEK_OF_YEAR,
  TO_CHAR(DATE_KEY, 'YYYY-MM')          AS YEAR_MONTH
FROM d;

CREATE OR REPLACE TABLE ANALYTICS.DIM_CUSTOMERS AS
SELECT
  CUSTOMER_ID,
  CUSTOMER_UNIQUE_ID,
  CUSTOMER_ZIP_PREFIX,
  CUSTOMER_CITY,
  CUSTOMER_STATE
FROM STG.CUSTOMERS;

CREATE OR REPLACE TABLE ANALYTICS.DIM_SELLERS AS
SELECT
  SELLER_ID,
  SELLER_ZIP_PREFIX,
  SELLER_CITY,
  SELLER_STATE
FROM STG.SELLERS;

CREATE OR REPLACE TABLE ANALYTICS.DIM_PRODUCTS AS
SELECT
  p.PRODUCT_ID,
  p.PRODUCT_CATEGORY_NAME,
  ct.PRODUCT_CATEGORY_NAME_ENGLISH       AS PRODUCT_CATEGORY_EN,
  p.PRODUCT_NAME_LENGTH,
  p.PRODUCT_DESCRIPTION_LENGTH,
  p.PRODUCT_PHOTOS_QTY,
  p.PRODUCT_WEIGHT_G,
  p.PRODUCT_LENGTH_CM,
  p.PRODUCT_HEIGHT_CM,
  p.PRODUCT_WIDTH_CM
FROM STG.PRODUCTS p
LEFT JOIN STG.CATEGORY_TRANSLATION ct
  ON ct.PRODUCT_CATEGORY_NAME = p.PRODUCT_CATEGORY_NAME;

CREATE OR REPLACE TABLE ANALYTICS.DIM_GEO_ZIP AS
SELECT
  ZIP_PREFIX,
  CITY,
  STATE,
  LAT_AVG,
  LNG_AVG,
  GEO_ROWS
FROM STG.GEO_ZIP;

-- ------------------------------------------------------------
-- Facts
-- ------------------------------------------------------------

-- Fact Orders (1 row per order)
-- Includes payment aggregation + review score + delivery durations
CREATE OR REPLACE TABLE ANALYTICS.FACT_ORDERS AS
WITH pay AS (
  SELECT
    ORDER_ID,
    SUM(PAYMENT_VALUE)                         AS TOTAL_PAYMENT_VALUE,
    MAX(PAYMENT_INSTALLMENTS)                  AS MAX_INSTALLMENTS,
    COUNT(*)                                   AS PAYMENT_ROWS
  FROM STG.PAYMENTS
  GROUP BY ORDER_ID
),
rev AS (
  SELECT
    ORDER_ID,
    AVG(REVIEW_SCORE)                          AS AVG_REVIEW_SCORE,
    COUNT(*)                                   AS REVIEW_ROWS
  FROM STG.REVIEWS
  GROUP BY ORDER_ID
)
SELECT
  o.ORDER_ID,
  o.CUSTOMER_ID,
  CAST(o.ORDER_PURCHASE_TS AS DATE)            AS ORDER_DATE,
  o.ORDER_STATUS,
  o.ORDER_PURCHASE_TS,
  o.ORDER_APPROVED_TS,
  o.ORDER_DELIVERED_CARRIER_TS,
  o.ORDER_DELIVERED_CUSTOMER_TS,
  o.ORDER_ESTIMATED_DELIVERY_TS,

  -- Durations (in days)
  DATEDIFF('day', o.ORDER_PURCHASE_TS, o.ORDER_DELIVERED_CUSTOMER_TS) AS DAYS_TO_DELIVER_CUSTOMER,
  DATEDIFF('day', o.ORDER_PURCHASE_TS, o.ORDER_DELIVERED_CARRIER_TS)  AS DAYS_TO_DELIVER_CARRIER,
  DATEDIFF('day', o.ORDER_ESTIMATED_DELIVERY_TS, o.ORDER_DELIVERED_CUSTOMER_TS) AS DAYS_LATE_VS_ESTIMATE,

  COALESCE(pay.TOTAL_PAYMENT_VALUE, 0)         AS TOTAL_PAYMENT_VALUE,
  pay.MAX_INSTALLMENTS,
  pay.PAYMENT_ROWS,

  rev.AVG_REVIEW_SCORE,
  rev.REVIEW_ROWS
FROM STG.ORDERS o
LEFT JOIN pay ON pay.ORDER_ID = o.ORDER_ID
LEFT JOIN rev ON rev.ORDER_ID = o.ORDER_ID;

-- Fact Order Items (line-level)
CREATE OR REPLACE TABLE ANALYTICS.FACT_ORDER_ITEMS AS
SELECT
  oi.ORDER_ID,
  oi.ORDER_ITEM_ID,
  oi.PRODUCT_ID,
  oi.SELLER_ID,
  CAST(o.ORDER_PURCHASE_TS AS DATE)            AS ORDER_DATE,
  o.ORDER_STATUS,
  oi.SHIPPING_LIMIT_TS,
  oi.PRICE,
  oi.FREIGHT_VALUE,
  (COALESCE(oi.PRICE,0) + COALESCE(oi.FREIGHT_VALUE,0)) AS LINE_TOTAL_VALUE
FROM STG.ORDER_ITEMS oi
LEFT JOIN STG.ORDERS o
  ON o.ORDER_ID = oi.ORDER_ID;

-- ------------------------------------------------------------
-- Power BI friendly “wide” view
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW ANALYTICS.VW_PBI_ORDER_ITEMS_WIDE AS
SELECT
  f.ORDER_ID,
  f.ORDER_ITEM_ID,
  f.ORDER_DATE,
  f.ORDER_STATUS,
  f.PRODUCT_ID,
  dp.PRODUCT_CATEGORY_NAME,
  dp.PRODUCT_CATEGORY_EN,
  f.SELLER_ID,
  ds.SELLER_CITY,
  ds.SELLER_STATE,
  dc.CUSTOMER_ID,
  dc.CUSTOMER_CITY,
  dc.CUSTOMER_STATE,
  dc.CUSTOMER_ZIP_PREFIX,
  gz.LAT_AVG  AS CUSTOMER_LAT,
  gz.LNG_AVG  AS CUSTOMER_LNG,
  f.PRICE,
  f.FREIGHT_VALUE,
  f.LINE_TOTAL_VALUE
FROM ANALYTICS.FACT_ORDER_ITEMS f
LEFT JOIN ANALYTICS.DIM_PRODUCTS dp ON dp.PRODUCT_ID = f.PRODUCT_ID
LEFT JOIN ANALYTICS.DIM_SELLERS ds  ON ds.SELLER_ID  = f.SELLER_ID
LEFT JOIN ANALYTICS.DIM_CUSTOMERS dc ON dc.CUSTOMER_ID = (
  SELECT o.CUSTOMER_ID FROM STG.ORDERS o WHERE o.ORDER_ID = f.ORDER_ID
)
LEFT JOIN ANALYTICS.DIM_GEO_ZIP gz ON gz.ZIP_PREFIX = dc.CUSTOMER_ZIP_PREFIX;

-- ------------------------------------------------------------
-- KPI Views
-- ------------------------------------------------------------

-- KPI: overview by month
CREATE OR REPLACE VIEW ANALYTICS.KPI_MONTHLY_OVERVIEW AS
SELECT
  TO_CHAR(ORDER_DATE, 'YYYY-MM') AS YEAR_MONTH,
  COUNT(*)                       AS ORDERS,
  SUM(TOTAL_PAYMENT_VALUE)       AS REVENUE,
  AVG(AVG_REVIEW_SCORE)          AS AVG_REVIEW_SCORE,
  AVG(DAYS_TO_DELIVER_CUSTOMER)  AS AVG_DAYS_TO_DELIVER
FROM ANALYTICS.FACT_ORDERS
GROUP BY 1
ORDER BY 1;

-- KPI: order status funnel
CREATE OR REPLACE VIEW ANALYTICS.KPI_ORDER_STATUS_FUNNEL AS
SELECT
  ORDER_STATUS,
  COUNT(*) AS ORDERS
FROM ANALYTICS.FACT_ORDERS
GROUP BY 1
ORDER BY ORDERS DESC;

-- KPI: delivery performance
CREATE OR REPLACE VIEW ANALYTICS.KPI_DELIVERY_PERFORMANCE AS
SELECT
  COUNT(*)                                                       AS ORDERS,
  AVG(DAYS_TO_DELIVER_CUSTOMER)                                  AS AVG_DAYS_TO_DELIVER,
  AVG(CASE WHEN DAYS_LATE_VS_ESTIMATE > 0 THEN 1 ELSE 0 END)      AS PCT_LATE,
  AVG(CASE WHEN DAYS_LATE_VS_ESTIMATE <= 0 THEN 1 ELSE 0 END)     AS PCT_ON_TIME_OR_EARLY,
  AVG(DAYS_LATE_VS_ESTIMATE)                                     AS AVG_DAYS_LATE_VS_ESTIMATE
FROM ANALYTICS.FACT_ORDERS
WHERE ORDER_DELIVERED_CUSTOMER_TS IS NOT NULL
  AND ORDER_ESTIMATED_DELIVERY_TS IS NOT NULL;

-- KPI: top categories by revenue (order-items based)
CREATE OR REPLACE VIEW ANALYTICS.KPI_TOP_CATEGORIES AS
SELECT
  COALESCE(dp.PRODUCT_CATEGORY_EN, dp.PRODUCT_CATEGORY_NAME) AS CATEGORY,
  SUM(f.LINE_TOTAL_VALUE)                                    AS REVENUE,
  COUNT(DISTINCT f.ORDER_ID)                                 AS ORDERS,
  COUNT(*)                                                   AS ORDER_ITEMS
FROM ANALYTICS.FACT_ORDER_ITEMS f
LEFT JOIN ANALYTICS.DIM_PRODUCTS dp ON dp.PRODUCT_ID = f.PRODUCT_ID
GROUP BY 1
ORDER BY REVENUE DESC;

-- KPI: top states by revenue (customer state)
CREATE OR REPLACE VIEW ANALYTICS.KPI_TOP_CUSTOMER_STATES AS
SELECT
  dc.CUSTOMER_STATE AS STATE,
  SUM(f.LINE_TOTAL_VALUE) AS REVENUE,
  COUNT(DISTINCT f.ORDER_ID) AS ORDERS
FROM ANALYTICS.FACT_ORDER_ITEMS f
LEFT JOIN STG.ORDERS o ON o.ORDER_ID = f.ORDER_ID
LEFT JOIN ANALYTICS.DIM_CUSTOMERS dc ON dc.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY 1
ORDER BY REVENUE DESC;

-- ------------------------------------------------------------
-- Quick verification
-- ------------------------------------------------------------
SELECT 'DIM_CUSTOMERS'     AS OBJ, COUNT(*) AS ROW_COUNT FROM ANALYTICS.DIM_CUSTOMERS
UNION ALL SELECT 'DIM_SELLERS'      , COUNT(*)           FROM ANALYTICS.DIM_SELLERS
UNION ALL SELECT 'DIM_PRODUCTS'     , COUNT(*)           FROM ANALYTICS.DIM_PRODUCTS
UNION ALL SELECT 'DIM_GEO_ZIP'      , COUNT(*)           FROM ANALYTICS.DIM_GEO_ZIP
UNION ALL SELECT 'FACT_ORDERS'      , COUNT(*)           FROM ANALYTICS.FACT_ORDERS
UNION ALL SELECT 'FACT_ORDER_ITEMS' , COUNT(*)           FROM ANALYTICS.FACT_ORDER_ITEMS;

